### ISSUE TITLE
AttributeError: 'Cursor' object has no attribute 'count'

### ISSUE THREAD

**Issue by rotty-dev** [nkrasn/g_man#3]
Hi, I'm having an issue trying to get the bot to run a command, I've setup a mongo database and I've verified that it's working but I get this error when running a command.

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Rotty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Rotty\Desktop\g_man-master\gman.py", line 56, in on_message
    media_cache.add_to_cache(message, message.attachments[0].url)
  File "C:\Users\Rotty\Desktop\g_man-master\media_cache.py", line 31, in add_to_cache
    channel_vids_count = channel_vids.count()
**AttributeError: 'Cursor' object has no attribute 'count'**

**Comment by nkrasn** [comment]
Hi, it seems to be an issue when using the latest version of pymongo. Try using pymongo==3.12.2 instead.
I'll update requirements.txt as well, it's a bit outdated at the moment.

**Comment by rotty-dev** [comment]
Works flawless! Thanks for updating the requirements file. Cheers!
